apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: user

  template:
    metadata:
      labels:
        app: user

    spec:
      containers:
        - name: user
          image: infrastructure-user-service:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 3000

          env:
            - name: PORT
              value: "3000"
            
            - name: DATABASE_URL
              value: "postgresql://postgres.zuowufunbzjyojaugbii:9YvQJkFZIMR177mf@aws-1-ap-south-1.pooler.supabase.com:6543/postgres"

            - name: SECRET_KEY
              value: "DBWEbhbsjdcbdsjcbsj"

            - name: JWT_SECRET
              value: "change_me"

            - name: REDIS_HOST
              value: redis-service

            - name: REDIS_PORT
              value: "6379"

            - name: KAFKA_BROKER
              value: "kafka-service:9092"
