# Use Node base image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy project files
COPY . .

# Build project
RUN npm run build

# Expose port (NestJS default)
EXPOSE 3000

# Run app
CMD ["npm", "run", "start:prod"]